weight = 2
# language code
languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# default amount of posts in each pages
paginate = 14
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

title = "Charles Chin's Blog"
contentDir = 'content/en'
