name: i18n
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Change permissions
        run: chmod 755 content

      - name: Create Translated Directories
        run: |
          mkdir -p content/posts/en
          mkdir -p content/posts/es
          mkdir -p content/posts/ar
          
      - name: Auto-i18n_translate
        env:
          # 设置环境变量
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          CHATGPT_API_BASE: ${{ secrets.CHATGPT_API_BASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python auto-translater.py || true
          
      - name: 设置 Git 配置
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 提交
        run: |
          git add .
          git commit -m "Add new posts via GitHub Actions" || echo "No new posts to commit."
          git push 
