name: i18n
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Change permissions
        run: chmod 755 /content
    
          
      - name: Auto-i18n_translate
        env:
          # 设置环境变量
          CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          CHATGPT_API_BASE: ${{ secrets.CHATGPT_API_BASE }}
        run: |
          pip install -r requirements.txt
          python auto-translater.py || true
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Save file"
          git push
