name: Build Hugo and Deploy
on:
  push:
    paths:
      - 'content/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        run: |
          rm themes/DoIt -rf
          git clone --depth 1 https://github.com/eallion/hugo-theme-doit.git themes/DoIt --single-branch
          hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify --enableGitInfo --templateMetrics --templateMetricsHints

      - name: Ready for Next.js
        run: |
          mkdir next
          cp public next/public -rf
          cp pages next/pages -rf
          cp vercel.json next/
          cp next.config.js next/
          cp package.json next/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.personal_token }}
          external_repository: xinkeji/xinkeji.github.io
          publish_branch: main
          publish_dir: ./next
          # destination_dir: public
          allow_empty_commit: true
          # commit_message: ${{ GitHub.event.head_commit.message }}
          full_commit_message: ${{ github.event.head_commit.message }}
          #cname: g0f.cn
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      # - name: Onionsite Pull Webhook
      #   uses: jasongitmail/fast-webhook@v1
      #   with:
      #     url: ${{ secrets.ONION_WEBHOOK_URL }}
      #     json: '{"onion": "pull"}'

      # - name: Algolia uploader
      #   uses: wangchucheng/algolia-uploader@master
      #   with:
      #     app_id: ${{ secrets.ALGOLIA_APPID }}
      #     admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      #     index_name: eallion
      #     index_file_path: public/index.json

      # - name: Algolia uploader English
      #   uses: wangchucheng/algolia-uploader@master
      #   with:
      #     app_id: ${{ secrets.ALGOLIA_APPID }}
      #     admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
      #     index_name: "eallion_blog_en"
      #     index_file_path: public/en/index.json

      # - name: Deploy to Aliyun OSS
      #   uses: fangbinwei/aliyun-oss-website-action@v1
      #   with:
      #     accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
      #     accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
      #     bucket: eallion-com
      #     endpoint: oss-cn-shanghai.aliyuncs.com
      #     folder: public
          # exclude: |
          #   tmp.txt

      # - name: Upload to Tencent COS CN
      #   uses: zkqiang/tencent-cos-action@v0.1.0
      #   with:
      #     args: upload -rsf --delete ./public/ /
      #     secret_id: ${{ secrets.SECRET_COS_ID }}
      #     secret_key: ${{ secrets.SECRET_COS_KEY }}
      #     bucket: ${{ secrets.COS_CN_BUCKET }}
      #     region: ap-shanghai

      # - name: Tencent CDN Purge
      #   uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
      #   env:
      #     SECRET_ID: ${{ secrets.SECRET_COS_ID }}
      #     SECRET_KEY: ${{ secrets.SECRET_COS_KEY }}
      #     PATHS: "https://g0f.cn/,https://www.g0f.cn/"
      #     FLUSH_TYPE: "delete" # optional

      # - name: Install TencentCloud CLI
      #   run: |
      #     pip install tccli

      # - name: Configure Tccli Credentials
      #   run: |
      #     tccli configure set secretId ${{ secrets.TENCENTCLOUD_TEO_SECRET_ID }}
      #     tccli configure set secretKey ${{ secrets.TENCENTCLOUD_TEO_SECRET_KEY }}

      # - name: Create Tencent Cloud TEO Purge Task
      #   run: |
      #     tccli teo CreatePurgeTask --cli-unfold-argument --ZoneId ${{ secrets.TENCENTCLOUD_TEO_ZONEID }} --Type purge_prefix --Method invalidate --Targets 'https://www.g0f.cn/'
